
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    depends_on:
      selenium:
        condition: service_healthy
    networks:
      - review-scraper-network
    restart: on-failure

  selenium:
    image: selenium/standalone-chrome:latest
    platform: linux/amd64
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC server (for debugging)
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_NO_PASSWORD=1
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - review-scraper-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    shm_size: '2gb'

networks:
  review-scraper-network:
    driver: bridge